package io.github.finagle.example.petstore

import javax.inject.Inject

import com.twitter.finagle.http.Request
import com.twitter.finatra.http.Controller

class PetstoreStoreController @Inject()(petstoreDb: PetstoreDb) extends Controller{
  /**
   * Endpoint for getInventory
   * @return A Router that contains a RequestReader of a Map reflecting the inventory.
   */
  get("/store/inventory") { request: Request =>
    petstoreDb.getInventory
  }

  /**
   * Endpoint for findOrder
   * The ID of the order to be found is passed in the path.
   * @return A Router that contains a RequestReader of the Order in question.
   */
  get("/store/order/:id") { request: Request =>
    request.params.getLong("id") match {
      case Some(id) => petstoreDb.findOrder(id)
      case None => throw MissingIdentifier("You must enter the id of the order to be found!")
    }
  }

  /**
   * Endpoint for addOrder
   * The order to be added is passed in the body.
   * @return A Router that contains a RequestReader of the autogenerated ID for the added Order.
   */
  post("/store/order") { order: Order =>
    petstoreDb.addOrder(order)
  }

  /**
   * Endpoint for deleteOrder
   * The ID of the order to be deleted is passed in the path.
   * @return A Router that contains a RequestReader of result of the deleteOrder method (true for success, false else).
   */
  delete("/store/order/:id") { request:Request =>
    request.params.getLong("id") match {
      case Some(id) => petstoreDb.deleteOrder(id)
      case None => throw MissingIdentifier("You must enter the id of the order to be deleted!")
    }
  }
}